import React from "react";
import { Copy, FileText, X } from "lucide-react";
import { Button } from "./ui/button";
import { toast } from "sonner";

interface ClaimSummaryProps {
    summary: string;
    onClose: () => void;
}

const ClaimSummary: React.FC<ClaimSummaryProps> = ({ summary, onClose }) => {
    const handleCopy = () => {
        navigator.clipboard.writeText(summary);
        toast.success("Summary copied to clipboard");
    };

    const parseBold = (text: string) => {
        const parts = text.split(/(\*\*.*?\*\*)/g);
        return parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={i} className="font-bold text-foreground">{part.slice(2, -2)}</strong>;
            }
            return part;
        });
    };

    const renderMarkdown = (text: string) => {
        // Simple line-by-line markdown-ish parser
        const lines = text.split('\n');
        return lines.map((line, index) => {
            const trimmedLine = line.trim();

            // Empty line
            if (!trimmedLine) return <div key={index} className="h-2" />;

            // Headers
            if (trimmedLine.startsWith('### ')) {
                return <h3 key={index} className="text-sm font-bold mt-4 mb-2 text-primary">{trimmedLine.slice(4)}</h3>;
            }
            if (trimmedLine.startsWith('## ')) {
                return <h2 key={index} className="text-base font-bold mt-5 mb-3 text-primary border-b border-border pb-1">{trimmedLine.slice(3)}</h2>;
            }
            if (trimmedLine.startsWith('# ')) {
                return <h1 key={index} className="text-lg font-bold mt-6 mb-4 text-primary">{trimmedLine.slice(2)}</h1>;
            }

            // Bullet points
            if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
                const content = trimmedLine.slice(2);
                return (
                    <div key={index} className="flex gap-2 ml-2 my-1">
                        <span className="text-primary mt-1.5">•</span>
                        <span>{parseBold(content)}</span>
                    </div>
                );
            }

            // Normal paragraph
            return <p key={index} className="my-1">{parseBold(line)}</p>;
        });
    };

    return (
        <div className="mt-6 animate-in fade-in slide-in-from-top-4 duration-300">
            <div className="p-6 rounded-xl border border-border bg-card shadow-sm">
                <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center gap-2">
                        <div className="p-2 rounded-lg bg-primary/10">
                            <FileText className="w-5 h-5 text-primary" />
                        </div>
                        <h2 className="text-lg font-bold text-foreground">
                            AI Claims Analysis Summary
                        </h2>
                    </div>
                    <div className="flex items-center gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleCopy}
                            className="text-xs h-8"
                        >
                            <Copy className="w-3.5 h-3.5 mr-1.5" />
                            Copy Report
                        </Button>
                        <Button
                            variant="ghost"
                            size="icon"
                            onClick={onClose}
                            className="h-8 w-8 text-muted-foreground hover:text-foreground"
                        >
                            <X className="w-4 h-4" />
                        </Button>
                    </div>
                </div>

                <div className="prose prose-sm dark:prose-invert max-w-none">
                    <div className="font-sans text-sm text-foreground/90 leading-relaxed bg-muted/30 p-5 rounded-lg border border-border/50">
                        {renderMarkdown(summary)}
                    </div>
                </div>

                <div className="mt-4 flex items-center gap-2 text-[10px] text-muted-foreground italic">
                    <span>* Generated by AI based on extracted claims data. Please verify financial totals.</span>
                </div>
            </div>
        </div>
    );
};

export default ClaimSummary;
